### ISSUE TITLE
Already finished?

### ISSUE THREAD

**Issue by d4h0** [flybayer/create-react-app-browser-extension#1]
Hi,

this project looks really nice.

There wasn't an update since 8 months so I'm wondering if the project is already completely finished or if it's dead / in hibernation mode (and I probably shouldn't use it to build my extension) :)

Best regards,
Daniel

**Comment by flybayer** [comment]
@bolus Hi Daniel! It's in hibernation unfortunately. It's way behind create-react-app right now. However, I do plan to get it back up to date and start using it again within the next 6 months unless something better exists by then.

You are welcome to work on updating it and submit a PR if you're interested.
